name: Build Native Addon

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # macOS builds
          - os: macos-latest
            arch: x64
            platform: darwin-x64
          - os: macos-latest
            arch: arm64
            platform: darwin-arm64

          # Linux builds
          - os: ubuntu-latest
            arch: x64
            platform: linux-x64
          - os: ubuntu-latest
            arch: arm64
            platform: linux-arm64

          # Windows build
          - os: windows-latest
            arch: x64
            platform: win32-x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Download SDL
        run: node scripts/download-sdl.mjs

      - name: Build native addon
        run: node scripts/build.mjs

      - name: Get package version
        id: package-version
        shell: bash
        run: echo "version=$(node -pe "JSON.parse(require('fs').readFileSync('package.json')).version")" >> $GITHUB_OUTPUT

      - name: Package binary (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          mkdir -p dist
          cd build/Release
          tar -czf ../../dist/gamepad-node-v${{ steps.package-version.outputs.version }}-${{ matrix.platform }}.tar.gz gamepad_native.node libSDL2*

      - name: Package binary (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          mkdir -p dist
          cd build/Release
          tar -czf ../../dist/gamepad-node-v${{ steps.package-version.outputs.version }}-${{ matrix.platform }}.tar.gz gamepad_native.node SDL2.dll

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: dist/gamepad-node-v${{ steps.package-version.outputs.version }}-${{ matrix.platform }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
